sudo: false

branches:
  only:
    - master
    - /^greenkeeper/.*$/

language: node_js

matrix:
  include:
    - node_js: "4"
    - node_js: "6"
    - node_js: "8"
      env: COVERALLS=1

before_install:
  - npm i -g lerna

install:
  - lerna bootstrap

after_success:
  - if [ "x$COVERALLS" = "x1" ]; then
      nyc report --reporter=text-lcov | npx coveralls;
    fi
