version: "{build}"

branches:
  only:
    - master
    - 3.x
    - /^greenkeeper/.*$/

environment:
  nodejs_version: "8"

install:
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - npm --version
  - npm install

test_script:
  - npm run unit

build: off
